PROFILE_PERMISSION_CATALOG: dict[str, str] = {
    "clients.dashboard.view": "Visualizar dashboard de clientes.",
    "clients.portfolio.view": "Visualizar carteira de clientes.",
    "clients.portfolio.evolution.view": "Visualizar evolucao da carteira.",
    "clients.dossier.view": "Abrir detalhe do cliente.",
    "clients.aging.import": "Importar AR Aging.",
    "clients.imports.history.view": "Visualizar historico de importacoes.",
    "credit.dashboard.view": "Visualizar dashboard de credito.",
    "credit.request.create": "Criar solicitacao de credito.",
    "credit.requests.view": "Visualizar solicitacoes de credito.",
    "credit.analysis.execute": "Executar analise de credito.",
    "credit.dossier.edit": "Editar dossie de credito.",
    "credit.request.submit": "Submeter solicitacao para aprovacao.",
    "credit.approval.approve": "Aprovar credito.",
    "credit.approval.reject": "Reprovar credito.",
    "credit.policy.view": "Visualizar politica de credito.",
    "credit.policy.manage": "Gerenciar politica de credito.",
    "company:view": "Visualizar empresa.",
    "company:manage": "Gerenciar empresa.",
    "bu:manage": "Gerenciar unidades de negocio.",
    "users:view": "Visualizar usuarios.",
    "users:manage": "Gerenciar usuarios.",
    "profiles:view": "Visualizar perfis.",
    "profiles:manage": "Gerenciar perfis.",
    "audit:view": "Visualizar auditoria.",
    "scope:all_bu": "Acesso total as unidades de negocio.",
}
